# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Passed_Tests',
            new_name='Passed_Test',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
