# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20181218_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='test',
            name='info',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
