# Generated by Django 2.1.4 on 2018-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20181219_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='info',
            field=models.TextField(default='None'),
        ),
    ]
