# Generated by Django 2.1.4 on 2018-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='None', max_length=50)),
                ('specialty', models.CharField(default='None', max_length=50)),
                ('info', models.TextField(default='None')),
            ],
        ),
        migrations.RemoveField(
            model_name='passed_test',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
